export const emptyFootnote = {
  children: [
    {
      direction: null,
      format: "",
      indent: 0,
      type: "para",
      version: 1,
      textFormat: 0,
      marker: "p",
      classList: ["text-spacing", "formatted-font"],
      children: [
        {
          type: "note",
          marker: "f",
          caller: "+",
          direction: null,
          format: "",
          indent: 0,
          version: 1,
          children: [
            {
              type: "immutable-note-caller",
              caller: "b",
              previewText:
                "The Hebrew text can be read either as established praise established strength",
              version: 1,
            },
            {
              type: "char",
              marker: "ft",
              text: "The Hebrew text can be read either as",
              detail: 0,
              format: 0,
              mode: "normal",
              style: "display: none",
              version: 1,
            },
            {
              type: "char",
              marker: "fqa",
              text: "established praise",
              detail: 0,
              format: 0,
              mode: "normal",
              style: "display: none",
              version: 1,
            },
            {
              type: "text",
              text: "or",
              detail: 0,
              format: 0,
              mode: "normal",
              style: "display: none",
              version: 1,
            },
            {
              type: "char",
              marker: "fqa",
              text: "established strength IIIII",
              detail: 0,
              format: 0,
              mode: "normal",
              style: "display: none",
              version: 1,
            },
            {
              type: "text",
              text: ".",
              detail: 0,
              format: 0,
              mode: "normal",
              style: "display: none",
              version: 1,
            },
          ],
        },
      ],
    },
  ],
};
