import { UsjDocument } from "../../core/usj";

/**
 * Milestones (ms) are used to mark alignments between different language texts.
 *
 * Two types of milestones are used:
 * - zaln-s: Start of alignment, contains metadata about the source word(s)
 * - zaln-e: End of alignment
 *
 * Simple alignment example:
 * {
 *   type: "ms",
 *   marker: "zaln-s",
 *   "x-content": "θεός",      // Original Greek word
 *   "x-lemma": "θεός",        // Dictionary form
 *   "x-morph": "Gr,N,,,,,NMS" // Morphology
 * }
 * { type: "char", marker: "w", content: ["God"] }        // English translation
 * { type: "ms", marker: "zaln-e" }
 *
 * Nested alignment example (multiple source words align to one phrase):
 * {
 *   type: "ms",
 *   marker: "zaln-s",
 *   "x-content": "ὁ"          // Greek article
 * }
 * {
 *   type: "ms",
 *   marker: "zaln-s",
 *   "x-content": "θεός"       // Greek noun
 * }
 * { type: "char", marker: "w", content: ["the God"] }    // Single English phrase
 * { type: "ms", marker: "zaln-e" }
 * { type: "ms", marker: "zaln-e" }
 */

export const titUsj: UsjDocument = {
  type: "USJ",
  version: "0.2.1",
  content: [
    {
      type: "book",
      marker: "id",
      code: "REV",
      content: [
        "EN_BSB en_English_ltr - Berean Study Bible Mon Apr 15 2024 16:09:49 GMT-0400 (Eastern Daylight Time) tc",
      ],
    },
    {
      type: "para",
      marker: "usfm",
      content: ["3.0"],
    },
    {
      type: "para",
      marker: "h",
      content: ["Revelation"],
    },
    {
      type: "para",
      marker: "toc1",
      content: ["Revelation"],
    },
    {
      type: "para",
      marker: "mt1",
      content: ["Revelation"],
    },
    {
      type: "chapter",
      marker: "c",
      number: "1",
      sid: "REV 1",
    },
    {
      type: "para",
      marker: "s1",
      content: ["Prologue"],
    },
    {
      type: "para",
      marker: "r",
      content: ["(Daniel 12:1–13)"],
    },
    {
      type: "para",
      marker: "b",
    },
    {
      type: "para",
      marker: "m",
      content: [
        {
          type: "verse",
          marker: "v",
          number: "1",
          sid: "REV 1:1",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G06020",
          "x-lemma": "ἀποκάλυψις",
          "x-morph": "Gr,N,,,,,NFS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἀποκάλυψις",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["This"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["is"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["the"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["revelation"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G24240",
          "x-lemma": "Ἰησοῦς",
          "x-morph": "Gr,N,,,,,GMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "Ἰησοῦ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["of"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["Jesus"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G55470",
          "x-lemma": "χριστός",
          "x-morph": "Gr,N,,,,,GMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "Χριστοῦ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["Christ"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        ", ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G37390",
          "x-lemma": "ὅς",
          "x-morph": "Gr,RR,,,,AFS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἣν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["which"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,NMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ὁ",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G23160",
          "x-lemma": "θεός",
          "x-morph": "Gr,N,,,,,NMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "Θεὸς",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["God"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G13250",
          "x-lemma": "δίδωμι",
          "x-morph": "Gr,V,IAA3,,S,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἔδωκεν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["gave"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G08460",
          "x-lemma": "αὐτός",
          "x-morph": "Gr,RP,,,3DMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "αὐτῷ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["Him"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G11660",
          "x-lemma": "δεικνύω",
          "x-morph": "Gr,V,NAA,,,,,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "δεῖξαι",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "3",
          content: ["to"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["show"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G08460",
          "x-lemma": "αὐτός",
          "x-morph": "Gr,RP,,,3GMS,",
          "x-occurrence": "1",
          "x-occurrences": "3",
          "x-content": "αὐτοῦ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "3",
          content: ["His"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,DMP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τοῖς",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G14010",
          "x-lemma": "δοῦλος",
          "x-morph": "Gr,N,,,,,DMP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "δούλοις",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["servants"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G37390",
          "x-lemma": "ὅς",
          "x-morph": "Gr,RR,,,,ANP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἃ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["what"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G12100",
          "x-lemma": "δέω",
          "x-morph": "Gr,V,IPA3,,S,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "δεῖ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["must"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G17220",
          "x-lemma": "ἐν",
          "x-morph": "Gr,P,,,,,D,,,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἐν",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G50340",
          "x-lemma": "τάχος",
          "x-morph": "Gr,N,,,,,DNS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τάχει",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["soon"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "note",
          marker: "f",
          caller: "+",
          content: [
            {
              type: "char",
              marker: "fr",
              content: ["1:1 "],
            },
            {
              type: "char",
              marker: "ft",
              content: ["Or suddenly or quickly"],
            },
          ],
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G10960",
          "x-lemma": "γίνομαι",
          "x-morph": "Gr,V,NAM,,,,,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "γενέσθαι",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["come"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "2",
          "x-occurrences": "3",
          content: ["to"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["pass"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        ". ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G45910",
          "x-lemma": "σημαίνω",
          "x-morph": "Gr,V,IAA3,,S,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἐσήμανεν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["He"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["made"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["it"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["known"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G06490",
          "x-lemma": "ἀποστέλλω",
          "x-morph": "Gr,V,PAA,NMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἀποστείλας",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["by"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["sending"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G08460",
          "x-lemma": "αὐτός",
          "x-morph": "Gr,RP,,,3GMS,",
          "x-occurrence": "2",
          "x-occurrences": "3",
          "x-content": "αὐτοῦ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "2",
          "x-occurrences": "3",
          content: ["His"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,GMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τοῦ",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G00320",
          "x-lemma": "ἄγγελος",
          "x-morph": "Gr,N,,,,,GMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἀγγέλου",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["angel"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,DMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τῷ",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G14010",
          "x-lemma": "δοῦλος",
          "x-morph": "Gr,N,,,,,DMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "δούλῳ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "3",
          "x-occurrences": "3",
          content: ["to"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G08460",
          "x-lemma": "αὐτός",
          "x-morph": "Gr,RP,,,3GMS,",
          "x-occurrence": "3",
          "x-occurrences": "3",
          "x-content": "αὐτοῦ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "3",
          "x-occurrences": "3",
          content: ["His"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,DMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τῷ",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G14010",
          "x-lemma": "δοῦλος",
          "x-morph": "Gr,N,,,,,DMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "δούλῳ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["servant"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G24910",
          "x-lemma": "Ἰωάννης",
          "x-morph": "Gr,N,,,,,DMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "Ἰωάννῃ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["John"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        ", ",
        {
          type: "verse",
          marker: "v",
          number: "2",
          sid: "REV 1:2",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G37390",
          "x-lemma": "ὅς",
          "x-morph": "Gr,RR,,,,NMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ὃς",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["who"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G31400",
          "x-lemma": "μαρτυρέω",
          "x-morph": "Gr,V,IAA3,,S,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἐμαρτύρησεν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["testifies"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G37450",
          "x-lemma": "ὅσος",
          "x-morph": "Gr,RR,,,,ANP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ὅσα",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["to"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["everything"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G37080",
          "x-lemma": "ὁράω",
          "x-morph": "Gr,V,IAA3,,S,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "εἶδεν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["he"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["saw"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        ". ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,AMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τὸν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["This"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["is"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "2",
          content: ["the"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G30560",
          "x-lemma": "λόγος",
          "x-morph": "Gr,N,,,,,AMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "λόγον",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["word"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,GMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τοῦ",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G23160",
          "x-lemma": "θεός",
          "x-morph": "Gr,N,,,,,GMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "Θεοῦ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "2",
          content: ["of"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["God"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G25320",
          "x-lemma": "καί",
          "x-morph": "Gr,CC,,,,,,,,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "καὶ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["and"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,AFS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τὴν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "2",
          "x-occurrences": "2",
          content: ["the"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G31410",
          "x-lemma": "μαρτυρία",
          "x-morph": "Gr,N,,,,,AFS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "μαρτυρίαν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["testimony"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G24240",
          "x-lemma": "Ἰησοῦς",
          "x-morph": "Gr,N,,,,,GMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "Ἰησοῦ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "2",
          "x-occurrences": "2",
          content: ["of"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["Jesus"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G55470",
          "x-lemma": "χριστός",
          "x-morph": "Gr,N,,,,,GMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "Χριστοῦ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["Christ"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        ".",
      ],
    },
    {
      type: "para",
      marker: "b",
    },
    {
      type: "para",
      marker: "m",
      content: [
        {
          type: "verse",
          marker: "v",
          number: "3",
          sid: "REV 1:3",
        },
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G31070",
          "x-lemma": "μακάριος",
          "x-morph": "Gr,NP,,,,NMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "μακάριος",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["Blessed"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "3",
          content: ["is"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,RD,,,,NMS,",
          "x-occurrence": "1",
          "x-occurrences": "2",
          "x-content": "ὁ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "3",
          content: ["the"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["one"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G03140",
          "x-lemma": "ἀναγινώσκω",
          "x-morph": "Gr,V,PPA,NMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἀναγινώσκων",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "2",
          content: ["who"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["reads"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["aloud"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,AMP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τοὺς",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "2",
          "x-occurrences": "3",
          content: ["the"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G30560",
          "x-lemma": "λόγος",
          "x-morph": "Gr,N,,,,,AMP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "λόγους",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["words"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G43940",
          "x-lemma": "προφητεία",
          "x-morph": "Gr,N,,,,,GFS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "προφητείας",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["of"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,GFS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τῆς",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["this"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G43940",
          "x-lemma": "προφητεία",
          "x-morph": "Gr,N,,,,,GFS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "προφητείας",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["prophecy"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        ", ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G25320",
          "x-lemma": "καί",
          "x-morph": "Gr,CC,,,,,,,,",
          "x-occurrence": "1",
          "x-occurrences": "2",
          "x-content": "καὶ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "2",
          content: ["and"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["blessed"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["are"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,RD,,,,NMP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "οἱ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["those"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G01910",
          "x-lemma": "ἀκούω",
          "x-morph": "Gr,V,PPA,NMP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἀκούοντες",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "2",
          "x-occurrences": "2",
          content: ["who"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["hear"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G25320",
          "x-lemma": "καί",
          "x-morph": "Gr,CC,,,,,,,,",
          "x-occurrence": "2",
          "x-occurrences": "2",
          "x-content": "καὶ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "2",
          "x-occurrences": "2",
          content: ["and"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G50830",
          "x-lemma": "τηρέω",
          "x-morph": "Gr,V,PPA,NMP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τηροῦντες",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["obey"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,RD,,,,ANP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "τὰ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["what"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G11250",
          "x-lemma": "γράφω",
          "x-morph": "Gr,V,PEP,ANP,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "γεγραμμένα",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "2",
          "x-occurrences": "3",
          content: ["is"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["written"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G17220",
          "x-lemma": "ἐν",
          "x-morph": "Gr,P,,,,,D,,,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἐν",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["in"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G08460",
          "x-lemma": "αὐτός",
          "x-morph": "Gr,RP,,,3DFS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "αὐτῇ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["it"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        ", ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G10630",
          "x-lemma": "γάρ",
          "x-morph": "Gr,CC,,,,,,,,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "γὰρ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["because"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G35880",
          "x-lemma": "ὁ",
          "x-morph": "Gr,EA,,,,NMS,",
          "x-occurrence": "2",
          "x-occurrences": "2",
          "x-content": "ὁ",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "3",
          "x-occurrences": "3",
          content: ["the"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G25400",
          "x-lemma": "καιρός",
          "x-morph": "Gr,N,,,,,NMS,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "καιρὸς",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["time"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        " ",
        {
          type: "ms",
          marker: "zaln-s",
          "x-strong": "G14510",
          "x-lemma": "ἐγγύς",
          "x-morph": "Gr,D,,,,,,,,,",
          "x-occurrence": "1",
          "x-occurrences": "1",
          "x-content": "ἐγγύς",
        },
        {
          type: "char",
          marker: "w",
          "x-occurrence": "3",
          "x-occurrences": "3",
          content: ["is"],
        },
        " ",
        {
          type: "char",
          marker: "w",
          "x-occurrence": "1",
          "x-occurrences": "1",
          content: ["near"],
        },
        {
          type: "ms",
          marker: "zaln-e",
        },
        ".",
      ],
    },
  ],
};
