import { generateId } from "./utils";

export const emptyCrossRefence = {
  children: [
    {
      children: [
        {
          children: [
            {
              children: [
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: "+",
                  type: "text",
                  version: 1,
                },
              ],
              direction: null,
              format: "",
              indent: 0,
              type: "inline",
              version: 1,
              attributes: {
                "perf-type": "paragraph",
                "data-namespace": "usfm",
                "data-marker": "x",
                "perf-subtype": "usfm:x",
                "data-caller": "+",
                class: "x",
              },
              tag: "span",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "graft",
          version: 1,
          attributes: {
            "perf-type": "graft",
            "perf-subtype": "note_caller",
            "perf-target": generateId(),
            class: "graft",
          },
          props: {
            isInline: true,
          },
          tag: "span",
        },
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: " ",
          type: "text",
          version: 1,
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: "normal",
              style: "",
              text: "1:1",
              type: "text",
              version: 1,
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "inline",
          version: 1,
          attributes: {
            "perf-type": "wrapper",
            "data-namespace": "usfm",
            "data-marker": "xo",
            "perf-subtype": "usfm:xo",
            class: "wrapper",
          },
          tag: "span",
        },
        {
          children: [],
          direction: null,
          format: "",
          indent: 0,
          type: "inline",
          version: 1,
          attributes: {
            "perf-type": "wrapper",
            "data-namespace": "usfm",
            "data-marker": "xt",
            "perf-subtype": "usfm:xt",
            class: "wrapper",
          },
          tag: "span",
        },
      ],
      direction: null,
      format: "",
      indent: 0,
      type: "inline",
      version: 1,
      attributes: {
        "perf-type": "paragraph",
        "data-namespace": "usfm",
        "data-marker": "x",
        "perf-subtype": "usfm:x",
        class: "x",
      },
      tag: "span",
    },
  ],
  direction: null,
  format: "",
  indent: 0,
  type: "graft",
  version: 1,
  attributes: {
    "perf-type": "graft",
    "perf-subtype": "xref",
    "perf-target": generateId(),
    class: "graft",
  },
  props: {
    isInline: true,
  },
  tag: "span",
};
