// Aux file with markers categorization to be used as a resource while generating a static markers map file
// Categorization is based on categorization in https://github.com/ubsicap/usfm/blob/master/sty/usfm.sty

export enum CategoryType {
  FileIdentification = "FileIdentification",
  Headers = "Headers",
  Remarks = "Remarks",
  Introduction = "Introduction",
  DivisionMarks = "DivisionMarks",
  Paragraphs = "Paragraphs",
  Poetry = "Poetry",
  TitlesHeadings = "TitlesHeadings",
  Tables = "Tables",
  CenterTables = "CenterTables",
  RightTables = "RightTables",
  Lists = "Lists",
  Footnotes = "Footnotes",
  CrossReferences = "CrossReferences",
  SpecialText = "SpecialText",
  CharacterStyling = "CharacterStyling",
  Breaks = "Breaks",
  SpecialFeatures = "SpecialFeatures",
  PeripheralReferences = "PeripheralReferences",
  PeripheralMaterials = "PeripheralMaterials",
  Uncategorized = "Uncategorized",
}

const categoriesMap: { [marker: string]: CategoryType } = {
  id: CategoryType.FileIdentification,
  usfm: CategoryType.FileIdentification,
  ide: CategoryType.FileIdentification,
  h: CategoryType.Headers,
  h1: CategoryType.Headers,
  h2: CategoryType.Headers,
  h3: CategoryType.Headers,
  toc1: CategoryType.Headers,
  toc2: CategoryType.Headers,
  toc3: CategoryType.Headers,
  toca1: CategoryType.Headers,
  toca2: CategoryType.Headers,
  toca3: CategoryType.Headers,
  rem: CategoryType.Remarks,
  sts: CategoryType.Remarks,
  restore: CategoryType.Remarks,
  imt: CategoryType.Introduction,
  imt1: CategoryType.Introduction,
  imt2: CategoryType.Introduction,
  imt3: CategoryType.Introduction,
  imt4: CategoryType.Introduction,
  imte: CategoryType.Introduction,
  imte1: CategoryType.Introduction,
  imte2: CategoryType.Introduction,
  is: CategoryType.Introduction,
  is1: CategoryType.Introduction,
  is2: CategoryType.Introduction,
  iot: CategoryType.Introduction,
  io: CategoryType.Introduction,
  io1: CategoryType.Introduction,
  io2: CategoryType.Introduction,
  io3: CategoryType.Introduction,
  io4: CategoryType.Introduction,
  ior: CategoryType.Introduction,
  ip: CategoryType.Introduction,
  im: CategoryType.Introduction,
  ipi: CategoryType.Introduction,
  imi: CategoryType.Introduction,
  ili: CategoryType.Introduction,
  ili1: CategoryType.Introduction,
  ili2: CategoryType.Introduction,
  ipq: CategoryType.Introduction,
  imq: CategoryType.Introduction,
  ipr: CategoryType.Introduction,
  ib: CategoryType.Introduction,
  iq: CategoryType.Introduction,
  iq1: CategoryType.Introduction,
  iq2: CategoryType.Introduction,
  iq3: CategoryType.Introduction,
  iex: CategoryType.Introduction,
  iqt: CategoryType.Introduction,
  ie: CategoryType.Introduction,
  c: CategoryType.DivisionMarks,
  ca: CategoryType.DivisionMarks,
  cp: CategoryType.DivisionMarks,
  cl: CategoryType.DivisionMarks,
  cd: CategoryType.DivisionMarks,
  v: CategoryType.DivisionMarks,
  va: CategoryType.DivisionMarks,
  vp: CategoryType.DivisionMarks,
  p: CategoryType.Paragraphs,
  m: CategoryType.Paragraphs,
  po: CategoryType.Paragraphs,
  pr: CategoryType.Paragraphs,
  cls: CategoryType.Paragraphs,
  pmo: CategoryType.Paragraphs,
  pm: CategoryType.Paragraphs,
  pmc: CategoryType.Paragraphs,
  pmr: CategoryType.Paragraphs,
  pi: CategoryType.Paragraphs,
  pi1: CategoryType.Paragraphs,
  pi2: CategoryType.Paragraphs,
  pi3: CategoryType.Paragraphs,
  pc: CategoryType.Paragraphs,
  mi: CategoryType.Paragraphs,
  nb: CategoryType.Paragraphs,
  q: CategoryType.Poetry,
  q1: CategoryType.Poetry,
  q2: CategoryType.Poetry,
  q3: CategoryType.Poetry,
  q4: CategoryType.Poetry,
  qc: CategoryType.Poetry,
  qr: CategoryType.Poetry,
  qs: CategoryType.Poetry,
  qa: CategoryType.Poetry,
  qac: CategoryType.Poetry,
  qm: CategoryType.Poetry,
  qm1: CategoryType.Poetry,
  qm2: CategoryType.Poetry,
  qm3: CategoryType.Poetry,
  qd: CategoryType.Poetry,
  b: CategoryType.Poetry,
  mt: CategoryType.TitlesHeadings,
  mt1: CategoryType.TitlesHeadings,
  mt2: CategoryType.TitlesHeadings,
  mt3: CategoryType.TitlesHeadings,
  mt4: CategoryType.TitlesHeadings,
  mte: CategoryType.TitlesHeadings,
  mte1: CategoryType.TitlesHeadings,
  mte2: CategoryType.TitlesHeadings,
  ms: CategoryType.TitlesHeadings,
  ms1: CategoryType.TitlesHeadings,
  ms2: CategoryType.TitlesHeadings,
  ms3: CategoryType.TitlesHeadings,
  mr: CategoryType.TitlesHeadings,
  s: CategoryType.TitlesHeadings,
  s1: CategoryType.TitlesHeadings,
  s2: CategoryType.TitlesHeadings,
  s3: CategoryType.TitlesHeadings,
  s4: CategoryType.TitlesHeadings,
  sr: CategoryType.TitlesHeadings,
  r: CategoryType.TitlesHeadings,
  sp: CategoryType.TitlesHeadings,
  d: CategoryType.TitlesHeadings,
  sd: CategoryType.TitlesHeadings,
  sd1: CategoryType.TitlesHeadings,
  sd2: CategoryType.TitlesHeadings,
  sd3: CategoryType.TitlesHeadings,
  sd4: CategoryType.TitlesHeadings,
  tr: CategoryType.Tables,
  th1: CategoryType.Tables,
  th2: CategoryType.Tables,
  th3: CategoryType.Tables,
  th4: CategoryType.Tables,
  th5: CategoryType.Tables,
  th6: CategoryType.Tables,
  th7: CategoryType.Tables,
  th8: CategoryType.Tables,
  th9: CategoryType.Tables,
  th10: CategoryType.Tables,
  th11: CategoryType.Tables,
  th12: CategoryType.Tables,
  tc1: CategoryType.Tables,
  tc2: CategoryType.Tables,
  tc3: CategoryType.Tables,
  tc4: CategoryType.Tables,
  tc5: CategoryType.Tables,
  tc6: CategoryType.Tables,
  tc7: CategoryType.Tables,
  tc8: CategoryType.Tables,
  tc9: CategoryType.Tables,
  tc10: CategoryType.Tables,
  tc11: CategoryType.Tables,
  tc12: CategoryType.Tables,
  thc1: CategoryType.CenterTables,
  thc2: CategoryType.CenterTables,
  thc3: CategoryType.CenterTables,
  thc4: CategoryType.CenterTables,
  thc5: CategoryType.CenterTables,
  thc6: CategoryType.CenterTables,
  thc7: CategoryType.CenterTables,
  thc8: CategoryType.CenterTables,
  thc9: CategoryType.CenterTables,
  thc10: CategoryType.CenterTables,
  thc11: CategoryType.CenterTables,
  thc12: CategoryType.CenterTables,
  tcc1: CategoryType.CenterTables,
  tcc2: CategoryType.CenterTables,
  tcc3: CategoryType.CenterTables,
  tcc4: CategoryType.CenterTables,
  tcc5: CategoryType.CenterTables,
  tcc6: CategoryType.CenterTables,
  tcc7: CategoryType.CenterTables,
  tcc8: CategoryType.CenterTables,
  tcc9: CategoryType.CenterTables,
  tcc10: CategoryType.CenterTables,
  tcc11: CategoryType.CenterTables,
  tcc12: CategoryType.CenterTables,
  thr1: CategoryType.RightTables,
  thr2: CategoryType.RightTables,
  thr3: CategoryType.RightTables,
  thr4: CategoryType.RightTables,
  thr5: CategoryType.RightTables,
  thr6: CategoryType.RightTables,
  thr7: CategoryType.RightTables,
  thr8: CategoryType.RightTables,
  thr9: CategoryType.RightTables,
  thr10: CategoryType.RightTables,
  thr11: CategoryType.RightTables,
  thr12: CategoryType.RightTables,
  tcr1: CategoryType.RightTables,
  tcr2: CategoryType.RightTables,
  tcr3: CategoryType.RightTables,
  tcr4: CategoryType.RightTables,
  tcr5: CategoryType.RightTables,
  tcr6: CategoryType.RightTables,
  tcr7: CategoryType.RightTables,
  tcr8: CategoryType.RightTables,
  tcr9: CategoryType.RightTables,
  tcr10: CategoryType.RightTables,
  tcr11: CategoryType.RightTables,
  tcr12: CategoryType.RightTables,
  lh: CategoryType.Lists,
  li: CategoryType.Lists,
  li1: CategoryType.Lists,
  li2: CategoryType.Lists,
  li3: CategoryType.Lists,
  li4: CategoryType.Lists,
  lf: CategoryType.Lists,
  lim: CategoryType.Lists,
  lim1: CategoryType.Lists,
  lim2: CategoryType.Lists,
  lim3: CategoryType.Lists,
  lim4: CategoryType.Lists,
  litl: CategoryType.Lists,
  lik: CategoryType.Lists,
  liv: CategoryType.Lists,
  liv1: CategoryType.Lists,
  liv2: CategoryType.Lists,
  liv3: CategoryType.Lists,
  liv4: CategoryType.Lists,
  liv5: CategoryType.Lists,
  f: CategoryType.Footnotes,
  fe: CategoryType.Footnotes,
  fr: CategoryType.Footnotes,
  ft: CategoryType.Footnotes,
  fk: CategoryType.Footnotes,
  fq: CategoryType.Footnotes,
  fqa: CategoryType.Footnotes,
  fl: CategoryType.Footnotes,
  fw: CategoryType.Footnotes,
  fp: CategoryType.Footnotes,
  fv: CategoryType.Footnotes,
  fdc: CategoryType.Footnotes,
  fm: CategoryType.Footnotes,
  x: CategoryType.CrossReferences,
  xo: CategoryType.CrossReferences,
  xop: CategoryType.CrossReferences,
  xt: CategoryType.CrossReferences,
  xta: CategoryType.CrossReferences,
  xk: CategoryType.CrossReferences,
  xq: CategoryType.CrossReferences,
  xot: CategoryType.CrossReferences,
  xnt: CategoryType.CrossReferences,
  xdc: CategoryType.CrossReferences,
  rq: CategoryType.CrossReferences,
  qt: CategoryType.SpecialText,
  nd: CategoryType.SpecialText,
  tl: CategoryType.SpecialText,
  dc: CategoryType.SpecialText,
  bk: CategoryType.SpecialText,
  sig: CategoryType.SpecialText,
  pn: CategoryType.SpecialText,
  png: CategoryType.SpecialText,
  addpn: CategoryType.SpecialText,
  wj: CategoryType.SpecialText,
  k: CategoryType.SpecialText,
  sls: CategoryType.SpecialText,
  ord: CategoryType.SpecialText,
  add: CategoryType.SpecialText,
  lit: CategoryType.SpecialText,
  no: CategoryType.CharacterStyling,
  it: CategoryType.CharacterStyling,
  bd: CategoryType.CharacterStyling,
  bdit: CategoryType.CharacterStyling,
  em: CategoryType.CharacterStyling,
  sc: CategoryType.CharacterStyling,
  sup: CategoryType.CharacterStyling,
  pb: CategoryType.Breaks,
  fig: CategoryType.SpecialFeatures,
  jmp: CategoryType.SpecialFeatures,
  pro: CategoryType.SpecialFeatures,
  rb: CategoryType.SpecialFeatures,
  w: CategoryType.PeripheralReferences,
  wh: CategoryType.PeripheralReferences,
  wg: CategoryType.PeripheralReferences,
  wa: CategoryType.PeripheralReferences,
  ndx: CategoryType.PeripheralReferences,
  periph: CategoryType.PeripheralMaterials,
  p1: CategoryType.PeripheralMaterials,
  p2: CategoryType.PeripheralMaterials,
  k1: CategoryType.PeripheralMaterials,
  k2: CategoryType.PeripheralMaterials,
  xtSee: CategoryType.PeripheralMaterials,
  xtSeeAlso: CategoryType.PeripheralMaterials,
};
export default categoriesMap;
