import perfDocument from "../../../data/tit.perf";
import lexicalState from "../../../data/tit.lexical";
import transformLexicalStateToPerf from ".";
import { SerializedUsfmElementNode } from "../../../nodes/UsfmElementNode";
import { PerfKind } from "../../../plugins/PerfOperations/types";

describe("Testing Perf To Lexical", () => {
  it("should convert perf to lexical", () => {
    const perfResult = transformLexicalStateToPerf(
      lexicalState.root as SerializedUsfmElementNode,
      PerfKind.Sequence,
    );
    const perfNode = {
      ...perfDocument,
      sequences: { ...perfResult.sequences, [perfDocument.main_sequence_id]: perfResult.result },
    };
    console.log({ perfNode });
    expect(perfNode).toEqual(perfDocument);
  });

  it("should convert block to lexical", () => {
    const block = {
      children: [
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: "normal",
              style: "",
              text: "2",
              type: "text",
              version: 1,
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "divisionmark",
          version: 1,
          attributes: {
            "perf-atts-number": "2",
            "perf-type": "mark",
            "perf-subtype": "verses",
            class: "verses",
          },
          tag: "span",
        },
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: "lesquelles reposent sur l’espérance de la vie éternelle, promise ",
          type: "text",
          version: 1,
        },
        {
          children: [
            {
              children: [
                {
                  children: [
                    {
                      children: [
                        {
                          detail: 0,
                          format: 0,
                          mode: "normal",
                          style: "",
                          text: "a",
                          type: "text",
                          version: 1,
                        },
                      ],
                      direction: "ltr",
                      format: "",
                      indent: 0,
                      type: "inline",
                      version: 1,
                      attributes: {
                        "perf-type": "paragraph",
                        "perf-subtype": "usfm:x",
                        class: "x",
                      },
                      tag: "span",
                    },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "graft",
                  version: 1,
                  attributes: {
                    "perf-type": "graft",
                    "perf-subtype": "note_caller",
                    "perf-target": "OGQzYmE5OTkt",
                    class: "graft",
                  },
                  tag: "span",
                },
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "text",
                  version: 1,
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "1.2 ",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xo",
                    class: "wrapper",
                  },
                  tag: "span",
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "No 23:19. 2s Ti 2:13.",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: "ltr",
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xt",
                    class: "wrapper",
                  },
                  tag: "span",
                },
              ],
              direction: null,
              format: "",
              indent: 0,
              type: "inline",
              version: 1,
              attributes: {
                "perf-type": "paragraph",
                "perf-subtype": "usfm:x",
                class: "x",
              },
              tag: "span",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "graft",
          version: 1,
          attributes: {
            "perf-type": "graft",
            "perf-subtype": "xref",
            "perf-target": "YjM5NGQ5NjAt",
            class: "graft",
          },
          tag: "span",
        },
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: "dès les plus anciens temps par le Dieu ",
          type: "text",
          version: 1,
        },
        {
          children: [
            {
              children: [
                {
                  children: [
                    {
                      children: [
                        {
                          detail: 0,
                          format: 0,
                          mode: "normal",
                          style: "",
                          text: "b",
                          type: "text",
                          version: 1,
                        },
                      ],
                      direction: null,
                      format: "",
                      indent: 0,
                      type: "inline",
                      version: 1,
                      attributes: {
                        "perf-type": "paragraph",
                        "perf-subtype": "usfm:x",
                        class: "x",
                      },
                      tag: "span",
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "graft",
                  version: 1,
                  attributes: {
                    "perf-type": "graft",
                    "perf-subtype": "note_caller",
                    "perf-target": "ZGQzZWY5Nzkt",
                    class: "graft",
                  },
                  tag: "span",
                },
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "text",
                  version: 1,
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "1.2 ",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xo",
                    class: "wrapper",
                  },
                  tag: "span",
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "Ro 16:25. Ép 1:9; 3:9. Col 1:26. 1 Pi 1:20.",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xt",
                    class: "wrapper",
                  },
                  tag: "span",
                },
              ],
              direction: null,
              format: "",
              indent: 0,
              type: "inline",
              version: 1,
              attributes: {
                "perf-type": "paragraph",
                "perf-subtype": "usfm:x",
                class: "x",
              },
              tag: "span",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "graft",
          version: 1,
          attributes: {
            "perf-type": "graft",
            "perf-subtype": "xref",
            "perf-target": "OTAyZGUyMTIt",
            class: "graft",
          },
          tag: "span",
        },
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: "qui ne ment point, ",
          type: "text",
          version: 1,
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: "normal",
              style: "",
              text: "3",
              type: "text",
              version: 1,
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "divisionmark",
          version: 1,
          attributes: {
            "perf-atts-number": "3",
            "perf-type": "mark",
            "perf-subtype": "verses",
            class: "verses",
          },
          tag: "span",
        },
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: "et qui a manifesté sa parole en son temps par la prédication ",
          type: "text",
          version: 1,
        },
        {
          children: [
            {
              children: [
                {
                  children: [
                    {
                      children: [
                        {
                          detail: 0,
                          format: 0,
                          mode: "normal",
                          style: "",
                          text: "c",
                          type: "text",
                          version: 1,
                        },
                      ],
                      direction: null,
                      format: "",
                      indent: 0,
                      type: "inline",
                      version: 1,
                      attributes: {
                        "perf-type": "paragraph",
                        "perf-subtype": "usfm:x",
                        class: "x",
                      },
                      tag: "span",
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "graft",
                  version: 1,
                  attributes: {
                    "perf-type": "graft",
                    "perf-subtype": "note_caller",
                    "perf-target": "NzNiZGIzYTkt",
                    class: "graft",
                  },
                  tag: "span",
                },
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "text",
                  version: 1,
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "1.3 ",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xo",
                    class: "wrapper",
                  },
                  tag: "span",
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "Ac 20:24. Ga 1:1.",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xt",
                    class: "wrapper",
                  },
                  tag: "span",
                },
              ],
              direction: null,
              format: "",
              indent: 0,
              type: "inline",
              version: 1,
              attributes: {
                "perf-type": "paragraph",
                "perf-subtype": "usfm:x",
                class: "x",
              },
              tag: "span",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "graft",
          version: 1,
          attributes: {
            "perf-type": "graft",
            "perf-subtype": "xref",
            "perf-target": "M2NjMjE3MGEt",
            class: "graft",
          },
          tag: "span",
        },
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: "qui m’a été confiée d’après l’ordre de Dieu notre Sauveur, ",
          type: "text",
          version: 1,
        },
        {
          children: [
            {
              detail: 0,
              format: 0,
              mode: "normal",
              style: "",
              text: "4",
              type: "text",
              version: 1,
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "divisionmark",
          version: 1,
          attributes: {
            "perf-atts-number": "4",
            "perf-type": "mark",
            "perf-subtype": "verses",
            class: "verses",
          },
          tag: "span",
        },
        {
          children: [
            {
              children: [
                {
                  children: [
                    {
                      children: [
                        {
                          detail: 0,
                          format: 0,
                          mode: "normal",
                          style: "",
                          text: "d",
                          type: "text",
                          version: 1,
                        },
                      ],
                      direction: null,
                      format: "",
                      indent: 0,
                      type: "inline",
                      version: 1,
                      attributes: {
                        "perf-type": "paragraph",
                        "perf-subtype": "usfm:x",
                        class: "x",
                      },
                      tag: "span",
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "graft",
                  version: 1,
                  attributes: {
                    "perf-type": "graft",
                    "perf-subtype": "note_caller",
                    "perf-target": "ODBmNzExNDgt",
                    class: "graft",
                  },
                  tag: "span",
                },
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "text",
                  version: 1,
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "1.4 ",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xo",
                    class: "wrapper",
                  },
                  tag: "span",
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "2 Co 2:12; 7:14; 8:6, 16. Ga 2:3.",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xt",
                    class: "wrapper",
                  },
                  tag: "span",
                },
              ],
              direction: null,
              format: "",
              indent: 0,
              type: "inline",
              version: 1,
              attributes: {
                "perf-type": "paragraph",
                "perf-subtype": "usfm:x",
                class: "x",
              },
              tag: "span",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "graft",
          version: 1,
          attributes: {
            "perf-type": "graft",
            "perf-subtype": "xref",
            "perf-target": "MDBiYzMyYzct",
            class: "graft",
          },
          tag: "span",
        },
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: "à Tite, mon enfant légitime en notre commune foi: ",
          type: "text",
          version: 1,
        },
        {
          children: [
            {
              children: [
                {
                  children: [
                    {
                      children: [
                        {
                          detail: 0,
                          format: 0,
                          mode: "normal",
                          style: "",
                          text: "e",
                          type: "text",
                          version: 1,
                        },
                      ],
                      direction: null,
                      format: "",
                      indent: 0,
                      type: "inline",
                      version: 1,
                      attributes: {
                        "perf-type": "paragraph",
                        "perf-subtype": "usfm:x",
                        class: "x",
                      },
                      tag: "span",
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "graft",
                  version: 1,
                  attributes: {
                    "perf-type": "graft",
                    "perf-subtype": "note_caller",
                    "perf-target": "YjllYzMwNmQt",
                    class: "graft",
                  },
                  tag: "span",
                },
                {
                  detail: 0,
                  format: 0,
                  mode: "normal",
                  style: "",
                  text: " ",
                  type: "text",
                  version: 1,
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "1.4 ",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xo",
                    class: "wrapper",
                  },
                  tag: "span",
                },
                {
                  children: [
                    {
                      detail: 0,
                      format: 0,
                      mode: "normal",
                      style: "",
                      text: "Ép 1:2. Col 1:2. 2 Ti 1:2. 1 Pi 1:2.",
                      type: "text",
                      version: 1,
                    },
                  ],
                  direction: null,
                  format: "",
                  indent: 0,
                  type: "inline",
                  version: 1,
                  attributes: {
                    "perf-type": "wrapper",
                    "perf-subtype": "usfm:xt",
                    class: "wrapper",
                  },
                  tag: "span",
                },
              ],
              direction: null,
              format: "",
              indent: 0,
              type: "inline",
              version: 1,
              attributes: {
                "perf-type": "paragraph",
                "perf-subtype": "usfm:x",
                class: "x",
              },
              tag: "span",
            },
          ],
          direction: null,
          format: "",
          indent: 0,
          type: "graft",
          version: 1,
          attributes: {
            "perf-type": "graft",
            "perf-subtype": "xref",
            "perf-target": "MTM0NTNmNDYt",
            class: "graft",
          },
          tag: "span",
        },
        {
          detail: 0,
          format: 0,
          mode: "normal",
          style: "",
          text: "que la grâce et la paix te soient données de la part de Dieu le Père et de Jésus-Christ notre Sauveur!",
          type: "text",
          version: 1,
        },
      ],
      direction: null,
      format: "",
      indent: 0,
      type: "usfmparagraph",
      version: 1,
      attributes: {
        "perf-type": "paragraph",
        "perf-subtype": "usfm:m",
        class: "paragraph",
      },
      tag: "p",
    };
    const perfBlock = transformLexicalStateToPerf(
      block as SerializedUsfmElementNode,
      PerfKind.Block,
    );
    const match = {
      result: {
        type: "paragraph",
        subtype: "usfm:x",
        content: [
          {
            type: "graft",
            subtype: "note_caller",
            target: "YzY2MTI2NjUt",
          },
          " ",
          {
            type: "wrapper",
            subtype: "usfm:xo",
            content: ["1.2 "],
          },
          {
            type: "wrapper",
            subtype: "usfm:xt",
            content: ["No 23:19. 2 Ti 2:13."],
          },
        ],
      },
      sequences: {
        YzY2MTI2NjUt: {
          type: "note_caller",
          blocks: [
            {
              type: "paragraph",
              subtype: "usfm:x",
              content: ["a"],
            },
          ],
        },
      },
    };
    console.log(perfBlock, match);
    expect(perfBlock).toEqual(match);
  });
});
